### ISSUE TITLE
Loading blocked due to disallowed MIME types

### ISSUE THREAD

**Issue by dgloeckner** [metrico/clickhouse-mate#20]
Hi,

this issue reproduces with any release as well as with a recent build of main branch.

I'm wondering how the DEMO instance actually works.

Here's the dump from Firefox web console:
```
Loading module from “http://localhost:8080/clickhouse-mate/runtime.1f1c374c947a5c42.js” was blocked because of a disallowed MIME type (“text/html”).
```
![image](https://user-images.githubusercontent.com/6209281/189297139-6661e80c-8b74-4f1f-bb1a-62eb15358071.png)

**Comment by lmangani** [comment]
@dgloeckner the demo instance runs off the `demo` branch which is static and ready to use anywhere.
We're bundling clickhouse-mate with other products just fine. What is the procedure you're trying to follow?

**Comment by dgloeckner** [comment]
I've tried to follow README.md
```
git clone https://github.com/metrico/clickhouse-mate
cd ./clickhouse-mate
npm run build
npm start
```

I've also tried to serve a release with NGINX
```
docker run -it --rm -d -p 8080:80 --name web -v /path/to/clickhouse-mate/release:/usr/share/nginx/html nginx
```

The result ist always as shown above.

I'm using MacOS and have tested with
![image](https://user-images.githubusercontent.com/6209281/189302815-3dfb9b79-f95a-4a18-8fd3-50bc3a4384b5.png)

and
![image](https://user-images.githubusercontent.com/6209281/189302891-726b952a-f408-4aa3-b146-b25147580fb7.png)

**Comment by dgloeckner** [comment]
As a workaround, I tried serving the contents of `demo` branch and that works.

**Comment by lmangani** [comment]
Thanks for confirming. The demo branch is built by this [github action](https://github.com/metrico/clickhouse-mate/blob/main/.github/workflows/build.yml)

**Comment by lmangani** [comment]
@RFbkak37y3kIY please check this
